apiVersion: v1
kind: Pod
metadata:
    name: configmappod
spec:
  containers:
  - name: configmapcontainer
    image: ubuntu
    command: ["sleep", "365d"]
    envFrom:
    - configMapRef:
        name: trainingconfigmap
